substitutions:
  name: womo-light-keller
  friendly_name: "WoMo Licht Keller"

  # Standard CCT Pins (global definiert)
  warm_white_pin: "GPIO3"
  cold_white_pin: "GPIO2"

  light_name: "Keller Licht"
  light_object_id: "keller_licht"

external_components:
  - source:
      type: local
      path: /config/components

packages:
  base: !include base/device_base.yaml
  node_health: !include base/node_health.yaml
  diag: !include common/diag_basic.yaml
  light: !include actuators/light_cct.yaml

mqtt:
  topic_prefix: womo/${name}
