substitutions:
  warm_white_pin: "GPIO3"
  cold_white_pin: "GPIO2"
  light_name: "CCT Light"
  light_object_id: "cct_light"

output:
  - platform: ledc
    id: warm_white_output
    pin: ${warm_white_pin}
    frequency: 20000 Hz

  - platform: ledc
    id: cold_white_output
    pin: ${cold_white_pin}
    frequency: 20000 Hz

light:
  - platform: cwww
    id: cct_light
    name: ${light_name}
    warm_white: warm_white_output
    cold_white: cold_white_output
    cold_white_color_temperature: 6500 K
    warm_white_color_temperature: 2700 K
    restore_mode: RESTORE_DEFAULT_OFF
