esphome:
  name: ${name}
  friendly_name: ${friendly_name}

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

logger:
  level: INFO
wifi:
  ssid: !secret wifi_ssid_2g
  password: !secret wifi_password_2g
  power_save_mode: none
  fast_connect: false
  output_power: 8.5
mqtt:
  broker: 10.10.64.10
  port: 1883
  username: esphome
  password: womo_mqtt_2026
  birth_message:
    topic: womo/system/${name}/status
    payload: online
    qos: 1
    retain: true
  will_message:
    topic: womo/system/${name}/status
    payload: offline
    qos: 1
    retain: true
  log_topic:
    topic: womo/debug/${name}
ota:
  - platform: esphome
    password: !secret ota_password
