text_sensor:
  - platform: wifi_info
    ip_address:
      name: "${friendly_name} IP"
      id: node_ip
      mqtt_id: node_ip_mqtt
      topic: womo/system/${name}/ip

  - platform: template
    name: "${friendly_name} Status"
    id: node_status
    update_interval: 60s
    mqtt_id: node_status_mqtt
    topic: womo/system/${name}/status
    lambda: |-
      return {"online"};

  - platform: template
    name: "${friendly_name} Restart Reason"
    id: node_restart_reason
    update_interval: 300s
    mqtt_id: node_restart_reason_mqtt
    topic: womo/system/${name}/restart_reason
    lambda: |-
      return {"unknown"};

sensor:
  - platform: uptime
    name: "${friendly_name} Uptime"
    id: node_uptime
    update_interval: 60s
    mqtt_id: node_uptime_mqtt
    topic: womo/system/${name}/uptime

  - platform: wifi_signal
    name: "${friendly_name} WiFi RSSI"
    id: node_wifi_rssi
    update_interval: 60s
    mqtt_id: node_wifi_rssi_mqtt
    topic: womo/system/${name}/wifi_rssi

  - platform: template
    name: "${friendly_name} Heap Free"
    id: node_heap_free
    unit_of_measurement: "B"
    accuracy_decimals: 0
    update_interval: 60s
    mqtt_id: node_heap_free_mqtt
    topic: womo/system/${name}/heap_free
    lambda: |-
      return (float) ESP.getFreeHeap();
