esphome:
  on_boot:
    then:
      - delay: 10s
      - mqtt.publish:
          topic: womo/system/${name}/ip
          payload: !lambda 'return id(node_ip).state;'
          qos: 1
          retain: true
      - mqtt.publish:
          topic: womo/system/${name}/restart_reason
          payload: !lambda 'return id(node_restart_reason).state;'
          qos: 1
          retain: true
      - mqtt.publish:
          topic: womo/system/${name}/uptime
          payload: !lambda 'return to_string((uint32_t) id(node_uptime).state);'
          qos: 1
          retain: true
      - mqtt.publish:
          topic: womo/system/${name}/wifi_rssi
          payload: !lambda 'return to_string((int) roundf(id(node_wifi_rssi).state));'
          qos: 1
          retain: true
      - mqtt.publish:
          topic: womo/system/${name}/heap_free
          payload: !lambda 'return to_string((uint32_t) id(node_heap_free).state);'
          qos: 1
          retain: true

interval:
  - interval: 60s
    then:
      - mqtt.publish:
          topic: womo/system/${name}/ip
          payload: !lambda 'return id(node_ip).state;'
          qos: 1
          retain: true
      - mqtt.publish:
          topic: womo/system/${name}/restart_reason
          payload: !lambda 'return id(node_restart_reason).state;'
          qos: 1
          retain: true
      - mqtt.publish:
          topic: womo/system/${name}/uptime
          payload: !lambda 'return to_string((uint32_t) id(node_uptime).state);'
          qos: 1
          retain: true
      - mqtt.publish:
          topic: womo/system/${name}/wifi_rssi
          payload: !lambda 'return to_string((int) roundf(id(node_wifi_rssi).state));'
          qos: 1
          retain: true
      - mqtt.publish:
          topic: womo/system/${name}/heap_free
          payload: !lambda 'return to_string((uint32_t) id(node_heap_free).state);'
          qos: 1
          retain: true

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "${friendly_name} IP"
      id: node_ip

  - platform: template
    name: "${friendly_name} Restart Reason"
    id: node_restart_reason
    update_interval: 300s
    lambda: |-
      return {"unknown"};

sensor:
  - platform: uptime
    name: "${friendly_name} Uptime"
    id: node_uptime
    update_interval: 60s

  - platform: wifi_signal
    name: "${friendly_name} WiFi RSSI"
    id: node_wifi_rssi
    update_interval: 60s

  - platform: template
    name: "${friendly_name} Heap Free"
    id: node_heap_free
    unit_of_measurement: "B"
    accuracy_decimals: 0
    update_interval: 60s
    lambda: |-
      return (float) ESP.getFreeHeap();
